global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'proposal'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['proposal:8080']

  - job_name: 'analise'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['analise:9999']

  - job_name: 'contas'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['contas:8888']

  - job_name: 'transacoes'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['transacoes:7777']